[server]
fileWatcherType = "poll"

[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#e0f0ff"
textColor = "#262730"
font = "sans serif"
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
